### PR TITLE
docs: updating initial_setup with an index and changing writing

### PR DESCRIPTION
**Pull request by On0n0k1**
I made some changes to "Initial Setup" page. I included an index at the start to help readers know what to expect from the page.

Are the changes according to expectations? Anything I should include or remove? Should I include an index for each page or remove this one?

Regards,
Lucas Lemos

### CODE REVIEW

**Comment by TheRustifyer** [comment]
> I made some changes to "Initial Setup" page. I included an index at the start to help readers know what to expect from the page.
> 
> Are the changes according to expectations? Anything I should include or remove? Should I include an index for each page or remove this one?
> 
> Regards, Lucas Lemos

Hey @On0n0k1 thanks for your contribution. I am running out of time today, but tomorrow I will review your PR.

**Review by TheRustifyer — APPROVED** [review]

**Comment by TheRustifyer** [comment]
@On0n0k1 changes are better than my expectations. I would suggest you to keep making a commit per page (or group of pages that fits well together). By the way, I am giving to you an invitation to our official Discord server. I would like you to join us there, so we can better track ideas and discussions, and, I would like you to add the Discord server in the documentation. Would be that possible?

**Comment by gbm25** [comment]
Hello, everyone.

First of all, thanks for the contribution!

Here is the link to the discord server https://discord.gg/MhwSymk7F6

Have a great day !

**Comment by On0n0k1** [comment]
Thanks. I will keep offering more updates and learn more about the source code to see how I can help further.

**Comment by TheRustifyer** [comment]
> Thanks. I will keep offering more updates and learn more about the source code to see how I can help further.

Remember to write us in Discord, so we can better tracking the changes. For example, today we'll publish a new relase with breaking changes, so we could tell you to document those new features/breaking changes if you keep working with the documentation

**Comment by On0n0k1** [comment]
Sure. I like writing documentation. I will have to ask in detail what changes were made so I can update properly.

**Comment by TheRustifyer** [comment]
> Sure. I like writing documentation. I will have to ask in detail what changes were made so I can update properly.

Sure. We just created a Discord channel just for that purpose, so we can continue this conversation further there!

**Comment by TheRustifyer** [comment]
@On0n0k1 I am converting this PR to draft while you're working

**Comment by On0n0k1** [comment]
I included the discord link. It was added to the "Introduction" page. Is that OK?

**Comment by TheRustifyer** [comment]
> I included the discord link. It was added to the "Introduction" page. Is that OK?

Yes. That's perfect, so people can reach us easily. Good thinking

**Comment by TheRustifyer** [comment]
Are you still planning to include more changes in the docs?

**Comment by On0n0k1** [comment]
I am. We still need to include an example to these tutorials. But currently I am busy with other assignments. So maybe next week I send the next commit.

I was thinking about reviewing the source code to include updates to the documentation in there as well. That will be helpful for me as well since I will learn more about the project as I send updates.

We also talked about including a Readme for the game examples you are developing. I could help with that as well.

**Comment by On0n0k1** [comment]
I think it could be better to merge these changes so that my commits doesn't slow down any future updates that need to be made in the future.

It is up to you. When deciding on an example, I will share it on discord before making a pull request. I'm still busy with other assignments.

**Pull request merged**
